### ISSUE TITLE
Practica de estimación de costos

### ISSUE THREAD

**Issue by Brendalp** [SistemasTecTlaxiaco/estimacion-de-costos-entrevista#1]
[Práctica de estimación de costos.pdf](https://github.com/SistemasTecTlaxiaco/estimacion-de-costos-entrevista/files/7575762/Practica.de.estimacion.de.costos.pdf)

**Comment by Edwin-1012** [comment]
Contiene todos los datos especificados dentro del Sprint 3.
Calificación: 100
Porcentaje: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
